# Dynamic Configuration for Swagger UI
http:
  routers:
    # Swagger UI для всех сервисов
    swagger-pinger:
      rule: "Host(`${DOMAIN:-localhost}`) && Path(`/swagger/pinger`)"
      entryPoints:
        - web
      service: pinger@docker
      middlewares:
        - swagger-rewrite-path
        - swagger-add-headers

    swagger-notificator:
      rule: "Host(`${DOMAIN:-localhost}`) && Path(`/swagger/notificator`)"
      entryPoints:
        - web
      service: notificator@docker
      middlewares:
        - swagger-rewrite-path
        - swagger-add-headers

    swagger-settings:
      rule: "Host(`${DOMAIN:-localhost}`) && Path(`/swagger/settings`)"
      entryPoints:
        - web
      service: settings@docker
      middlewares:
        - swagger-rewrite-path
        - swagger-add-headers

    swagger-statistics:
      rule: "Host(`${DOMAIN:-localhost}`) && Path(`/swagger/statistics`)"
      entryPoints:
        - web
      service: statistics@docker
      middlewares:
        - swagger-rewrite-path
        - swagger-add-headers

  middlewares:
    swagger-rewrite-path:
      replacePathRegex:
        regex: "^/swagger/([^/]+)(/.*)?$"
        replacement: "/swagger-ui.html"

    swagger-add-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "http"
          X-Forwarded-Host: "${DOMAIN:-localhost}"