package ru.oldzoomer.pingtower.statistics.cassandra.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.springframework.data.cassandra.core.cql.PrimaryKeyType;
import org.springframework.data.cassandra.core.mapping.PrimaryKey;
import org.springframework.data.cassandra.core.mapping.PrimaryKeyClass;
import org.springframework.data.cassandra.core.mapping.PrimaryKeyColumn;
import org.springframework.data.cassandra.core.mapping.Table;

import lombok.*;


@Getter
@Setter
@Table("aggregated_check_results")
public class AggregatedCheckResult {
    @PrimaryKey
    private AggregatedCheckResultKey key;
    
    private Integer upCount;
    private Integer downCount;
    private Integer unknownCount;
    private Double avgResponseTime;
    private Integer minResponseTime;
    private Integer maxResponseTime;
    
    @Getter
    @Setter
    @PrimaryKeyClass
    public static class AggregatedCheckResultKey implements Serializable {
        @PrimaryKeyColumn(name = "check_id", type = PrimaryKeyType.PARTITIONED)
        private String checkId;
        
        @PrimaryKeyColumn(name = "aggregation_interval", type = PrimaryKeyType.CLUSTERED)
        private String aggregationInterval; // MINUTE, HOUR, DAY, WEEK, MONTH
        
        @PrimaryKeyColumn(name = "timestamp", type = PrimaryKeyType.CLUSTERED)
        private LocalDateTime timestamp;
        
        // equals and hashCode methods are automatically generated by Lombok
    }
}