package ru.oldzoomer.pingtower.statistics.cassandra.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Map;

import org.springframework.data.cassandra.core.cql.PrimaryKeyType;
import org.springframework.data.cassandra.core.mapping.PrimaryKey;
import org.springframework.data.cassandra.core.mapping.PrimaryKeyClass;
import org.springframework.data.cassandra.core.mapping.PrimaryKeyColumn;
import org.springframework.data.cassandra.core.mapping.Table;

import lombok.*;

@Getter
@Setter
@Table("raw_check_results")
public class RawCheckResult {
    @PrimaryKey
    private RawCheckResultKey key;
    
    private String status;
    private Integer responseTime;
    private Integer httpStatusCode;
    private String errorMessage;
    private Map<String, String> metrics;
    
    @Getter
    @Setter
    @PrimaryKeyClass
    public static class RawCheckResultKey implements Serializable {
        @PrimaryKeyColumn(name = "check_id", type = PrimaryKeyType.PARTITIONED)
        private String checkId;
        
        @PrimaryKeyColumn(name = "timestamp", type = PrimaryKeyType.CLUSTERED)
        private LocalDateTime timestamp;
        
        // equals and hashCode methods are automatically generated by Lombok
    }
}